// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_retrieval.proto

// Protobuf Java Version: 3.25.1
package csc435.app.protogen;

public interface ConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ConnectRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ConnectRequest.Type type = 1;</code>
   * @return The type.
   */
  csc435.app.protogen.ConnectRequest.Type getType();

  /**
   * <code>string clientId = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
