// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_retrieval.proto

// Protobuf Java Version: 3.25.1
package csc435.app.protogen;

public interface ConnectReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConnectReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool connected = 2;</code>
   * @return The connected.
   */
  boolean getConnected();
}
