// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_retrieval.proto

// Protobuf Java Version: 3.25.1
package csc435.app.protogen;

public final class FileRetrievalProto {
  private FileRetrievalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexRequest_WordCountEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexRequest_WordCountEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024file_retrieval.proto\"k\n\016ConnectRequest" +
      "\022\"\n\004type\030\001 \001(\0162\024.ConnectRequest.Type\022\020\n\010" +
      "clientId\030\002 \001(\t\"#\n\004Type\022\013\n\007CONNECT\020\000\022\016\n\nD" +
      "ISCONNECT\020\001\"!\n\014ConnectReply\022\021\n\tconnected" +
      "\030\002 \001(\010\"\203\001\n\014IndexRequest\022\020\n\010filename\030\001 \001(" +
      "\t\022/\n\twordCount\030\002 \003(\0132\034.IndexRequest.Word" +
      "CountEntry\0320\n\016WordCountEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\005:\0028\001\"\035\n\nIndexReply\022\017\n\007in" +
      "dexed\030\001 \001(\010\"p\n\rSearchRequest\022!\n\004type\030\001 \001" +
      "(\0162\023.SearchRequest.Type\022\r\n\005word1\030\002 \001(\t\022\r" +
      "\n\005word2\030\003 \001(\t\"\036\n\004Type\022\n\n\006SINGLE\020\000\022\n\n\006DOU" +
      "BLE\020\001\"\034\n\013SearchReply\022\r\n\005files\030\001 \003(\t2\215\001\n\r" +
      "FileRetrieval\022%\n\005Index\022\r.IndexRequest\032\013." +
      "IndexReply\"\000\022(\n\006Search\022\016.SearchRequest\032\014" +
      ".SearchReply\"\000\022+\n\007Connect\022\017.ConnectReque" +
      "st\032\r.ConnectReply\"\000B+\n\023csc435.app.protog" +
      "enB\022FileRetrievalProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectRequest_descriptor,
        new java.lang.String[] { "Type", "ClientId", });
    internal_static_ConnectReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConnectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectReply_descriptor,
        new java.lang.String[] { "Connected", });
    internal_static_IndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexRequest_descriptor,
        new java.lang.String[] { "Filename", "WordCount", });
    internal_static_IndexRequest_WordCountEntry_descriptor =
      internal_static_IndexRequest_descriptor.getNestedTypes().get(0);
    internal_static_IndexRequest_WordCountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexRequest_WordCountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_IndexReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_IndexReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexReply_descriptor,
        new java.lang.String[] { "Indexed", });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Type", "Word1", "Word2", });
    internal_static_SearchReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SearchReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchReply_descriptor,
        new java.lang.String[] { "Files", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
