// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_retrieval.proto

// Protobuf Java Version: 3.25.1
package csc435.app.protogen;

public interface IndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>map&lt;string, int32&gt; wordCount = 2;</code>
   */
  int getWordCountCount();
  /**
   * <code>map&lt;string, int32&gt; wordCount = 2;</code>
   */
  boolean containsWordCount(
      java.lang.String key);
  /**
   * Use {@link #getWordCountMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getWordCount();
  /**
   * <code>map&lt;string, int32&gt; wordCount = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getWordCountMap();
  /**
   * <code>map&lt;string, int32&gt; wordCount = 2;</code>
   */
  int getWordCountOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; wordCount = 2;</code>
   */
  int getWordCountOrThrow(
      java.lang.String key);
}
