// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_retrieval.proto

// Protobuf Java Version: 3.25.1
package csc435.app.protogen;

public interface IndexReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool indexed = 1;</code>
   * @return The indexed.
   */
  boolean getIndexed();
}
