// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_retrieval.proto

// Protobuf Java Version: 3.25.1
package csc435.app.protogen;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SearchRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.SearchRequest.Type type = 1;</code>
   * @return The type.
   */
  csc435.app.protogen.SearchRequest.Type getType();

  /**
   * <code>string word1 = 2;</code>
   * @return The word1.
   */
  java.lang.String getWord1();
  /**
   * <code>string word1 = 2;</code>
   * @return The bytes for word1.
   */
  com.google.protobuf.ByteString
      getWord1Bytes();

  /**
   * <code>string word2 = 3;</code>
   * @return The word2.
   */
  java.lang.String getWord2();
  /**
   * <code>string word2 = 3;</code>
   * @return The bytes for word2.
   */
  com.google.protobuf.ByteString
      getWord2Bytes();
}
